### ISSUE TITLE
How to set po files location in ASP.NET Core example

### ISSUE THREAD

**Issue by nkosi23** [adams85/po#21]
Hello,

First of all thank you for this wonderful library! I am trying to integrate it with ASP.NET Core Razor Pages, however my translations are not found, I get the following log message:

`Translation for 'Welcome' in culture 'fr-FR' was not found at the following location(s): My.Assembly.Name`

I am having a hard time trying to figure out where to my translation files. My folder structure is the following:

```
MyProjectFolder/
   Translations/
        MyProjectName.pot
        en-US/
            MyProjectName.po
        fr-FR/
            MyProjectName.po
```

 My am I wondering is:

1. What is the default folder structure the library is expecting
2. How can we configure the location of the po files?

Thank you!

**Comment by adams85** [comment]
Hi!

Just to be clear, you're using the *WebAppLocalization* sample as the starting point for your application, right?

If so, [that localizer implementation looks for the translation **in the PO file whose name matches the *location* of the localizer object**](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/Infrastructure/Localization/POStringLocalizer.cs#L64). Location is just an arbitrary string. You can create localizer objects with whatever location you like [using this method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizerfactory.create?view=dotnet-plat-ext-6.0&viewFallbackFrom=net-6.0#microsoft-extensions-localization-istringlocalizerfactory-create(system-string-system-string)).

However, usually we don't do that, just inject a `IStringLocalizer<SomeType>`. Under the hood this results in a call to [the other `Create` overload](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizerfactory.create?view=dotnet-plat-ext-6.0#microsoft-extensions-localization-istringlocalizerfactory-create(system-type)) accepting a `Type` parameter. If you take a look at [how this is implemented in this case](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/Infrastructure/Localization/POStringLocalizerFactory.cs#L20), you can see that the type's (simple) assembly name is used as the location (unless you override this default behavior by annotating your type with an `AssociatedAssemblyNameAttribute`). For example, if you inject `IStringLocalizer<SomeType>`, where `SomeType` resides in *SomeAssembly.dll*, all the translations done via that localizer instance will be looked up in the file named *SomeAssembly.po* (within the directory corresponding to the current culture).

So I suspect that you have this issue because your application's assembly name and the name of your PO files mismatch. To make this work, you need to create (or make the extractor tool, POTools create) POT/PO files with the correct file name which matches the name of your assembli(es), as it's shown in the sample project:
* [project configuration](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/WebAppLocalization.csproj#L5)
* [extractor script](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/Translations/extract.cmd#L14).

**Comment by adams85** [comment]
> However, what is puzzling me here is that I have just checked and the name of the .po files already match the name of the Assembly

Can you show me your code (or an MRE) maybe? Without that, I can only make guesses. However, I think you need to do some debugging around [`POStringLocalizer.GetCatalog`](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/Infrastructure/Localization/POStringLocalizer.cs#L58)

**Comment by adams85** [comment]
> The language names use a "_" instead of a "-" could it be the cause of the issue?

Language name is irrelevant, `file.Key.Culture` is [what's used as part of the lookup key](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/Infrastructure/Localization/DefaultTranslationsProvider.cs#L40).

However, the ctor of `CultureInfo` also accepts the "en_US" format besides "en-US". That might cause problems indeed.

**Comment by adams85** [comment]
Before you create a repro, could you do a debug session and verify whether the correct catalog is found or not [at this line](https://github.com/adams85/po/blob/1.8.0/samples/WebAppLocalization/Infrastructure/Localization/POStringLocalizer.cs#L64)?

**Comment by adams85** [comment]
My extractor tool supports display/data annotations but it's done slightly differently: for example, see [this code](https://github.com/adams85/aspnetskeleton2/blob/a19728c930811bb1e15ba3d05729f3ad01830693/src/Service.Contract/Settings/SettingData.cs).

Of course, if this doesn't suit your needs, you're free to clone and modify the tool as you wish.

Please be aware though that properly localizing data annotations in ASP.NET Core is a PITA. I made it work in my template project but it required some further steps like [this](https://github.com/adams85/aspnetskeleton2/blob/master/src/Api/Infrastructure/DataAnnotations/DataAnnotationsLocalizationAdjuster.cs) and [this](https://github.com/adams85/aspnetskeleton2/blob/a19728c930811bb1e15ba3d05729f3ad01830693/src/Api/Startup.Mvc.cs#L57-L75).

**Comment by adams85** [comment]
Yep, constants and enums annotated with the `Localize` attribute are extracted.
