### ISSUE TITLE
Creating a POT file

### ISSUE THREAD

**Issue by nkosi23** [adams85/po#24]
Hello,

I am looking into adding localization to an application developed in F#, and since there is no tool to extract translatable strings from .fs fsharp source files, I am thinking about building some sort of global dictionary containing all translatable strings, so that all i'd have to do is iterate over all keys and use your library to build a pot catalog (thus removing the need to parse arbitrary source files).

However, since I am not yet super familiar with gettext tools, I am looking for pointers on how to build a pot file using your library. From what I understand, the difference between .pot and .po files is that pot files are empty template files. My understanding is that I need to generate a pot file since the output would then be used to create the various language specific .po files using poedit.

The samples of the README file seem to be focused on creating a .po file for a specific language, any pointer on building a .pot file instead? Many thanks!

**Comment by adams85** [comment]
Hi @nkosi23,

I suggest you take a look at my extractor tool a.k.a. [POTools](https://github.com/adams85/aspnetskeleton2/tree/master/tools/POTools). Although it's built for extracting translatable strings from C# code, I think it's all there what you need to accomplish your goals. You find the POT builder logic [here](https://github.com/adams85/aspnetskeleton2/blob/master/tools/POTools/Commands/ExtractCommand.cs#L122).

In short, the tool's `extract` command works like this: it extracts translatable texts from the source files whose path you feed to it and build a POT file from the extracted texts. If there's already a POT file with the same name, the tool is capable of merging the the old and the new POT files and marking the changed entries (new/changed/removed) using flag comments.

However, this is only one part of the equation. POT files just contain the extracted, untranslated texts. To make this actually useful, you need to create PO files from the POT file for each supported language using some editor tool like POEdit. In your application you load and use the PO files which contain the actual translations.

Now, that's all well and good until your app's translatable strings change. Then you need to re-extract them and update the POT and PO files. As I already mentioned above, POTools is able to compute and mark the changes. Not only can do that for POT files, but also for PO files. So the translators will know what translations have changes, what new texts have been added, etc. (IIRC, POEdit has some update/merge features as well but I have no experience with that because POTools covers all I need).

To get a deeper understanding, I recommend feeding some C# code file to POTools' `extract` command and debugging it to get familiar with how it works internally, how it builds PO catalogs, etc. You can also find [here](https://github.com/adams85/aspnetskeleton2/blob/master/src/Service/Translations/extract.cmd) an example of "real world usage".

Hope this helps and feel free to ask further questions if something's not clear.

**Comment by adams85** [comment]
1. As the variable name suggests, all the extracted translatable texts are grouped by id, where id is actually a triplet: (entry id, plural entry id, context id). These three components identify a PO entry, you can have only a single entry per catalog with a unique combination of these. There is even a dedicated type to represent such ids: `POKey`.

   The extractor uses the extracted text as the entry id, however, when you want pluralization support for that entry, you can specify a plural entry id using the `Plural` type like [this](https://github.com/adams85/po/blob/4c53b0d9e9eb0ac10af7481b131566008bfad460/samples/WebAppLocalization/Pages/Index.cshtml.cs#L44). There is a context id as well, which can be used to differentiate texts which has the same entry+plural entry id but needs different translation. You can specify a context id using the `TextContext` type like [this](https://github.com/adams85/po/blob/master/samples/WebAppLocalization/Pages/Index.cshtml#L4).

   These types (`Plural` and `TextContext`) are defined in the [Karambolo.Common](https://github.com/adams85/common/tree/master/source/Karambolo.Common/Localization) library but you don't need to reference that. You can just copy&paste these types into your project - if you need them at all.

2. Your understanding is correct. This piece of code just makes sure that in a PO file there are not more translations (`msgstr[]` items) for an entry than the number of plural forms in the given language.

3. In the case of an entry, `Count` means the number of translations (`msgstr[]` items) specified for that entry.

4. In short, it tells the translator to revise that entry. See also See https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/gettext.html#Fuzzy-Entries

5. I think I've already answered this question above.

Again, I suggest examining the extractor's code in action to get familiar with the PO building/merging logic. You can use [the sample project](https://github.com/adams85/po/tree/master/samples/WebAppLocalization) as a "guinea pig". For example, extract the texts from it by `POTools.exe scan -p WebAppLocalization.csproj > extracted.txt`. Then set a breakpoint somewhere [here](https://github.com/adams85/aspnetskeleton2/blob/0b5b6ff7625993c9a89bfbdcd0226a137eac319d/tools/POTools/Commands/ExtractCommand.cs#L371), setup your IDE to start a debug session with the command line arguments `extract -o app.pot -m -l en-US < extracted.txt` and step through the code while examining the variables and method parameters.

**Comment by adams85** [comment]
Sure thing! You can find a link on the [project page](https://github.com/adams85/po#karambolopo).
